/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentPracticeSessionIdRouteImport } from './routes/student.practice.$sessionId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentPracticeSessionIdRoute =
  StudentPracticeSessionIdRouteImport.update({
    id: '/student/practice/$sessionId',
    path: '/student/practice/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/teacher': typeof TeacherRoute
  '/student/login': typeof StudentLoginRoute
  '/student/': typeof StudentIndexRoute
  '/student/practice/$sessionId': typeof StudentPracticeSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/teacher': typeof TeacherRoute
  '/student/login': typeof StudentLoginRoute
  '/student': typeof StudentIndexRoute
  '/student/practice/$sessionId': typeof StudentPracticeSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/teacher': typeof TeacherRoute
  '/student/login': typeof StudentLoginRoute
  '/student/': typeof StudentIndexRoute
  '/student/practice/$sessionId': typeof StudentPracticeSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/teacher'
    | '/student/login'
    | '/student/'
    | '/student/practice/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/teacher'
    | '/student/login'
    | '/student'
    | '/student/practice/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/teacher'
    | '/student/login'
    | '/student/'
    | '/student/practice/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  TeacherRoute: typeof TeacherRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentPracticeSessionIdRoute: typeof StudentPracticeSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/practice/$sessionId': {
      id: '/student/practice/$sessionId'
      path: '/student/practice/$sessionId'
      fullPath: '/student/practice/$sessionId'
      preLoaderRoute: typeof StudentPracticeSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  TeacherRoute: TeacherRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentPracticeSessionIdRoute: StudentPracticeSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
